/// Flutter icons MyFlutterIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterIcon
///      fonts:
///       - asset: fonts/MyFlutterIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterIcon {
  MyFlutterIcon._();

  static const _kFontFam = 'MyFlutterIcon';
  static const String? _kFontPkg = null;

  static const IconData perm_identity = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nose = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dermatology = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laboratory = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chest = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bone_healthcare_and_medical = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fitness_body = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData family = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ear = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardiology = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nephrology_1 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rheumatology = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Cardiology_and_Vascular_Disease = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_pharmacy = IconData(0xe9ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe9f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital = IconData(0xf0f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital_alt = IconData(0xf47d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tooth = IconData(0xf5c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital_user = IconData(0xf80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
